#!/usr/bin/env bash
# claude-setup installer: global CLAUDE.md, subagents, hooks, /commit, Obsidian vault,
# MCP servers, skills and the Jev plugin. Idempotent: re-running applies only what changed,
# including changes to .env.
#
#   ./install.sh            install / update everything
#   ./install.sh --offline  skip MCP servers, skills and plugins (local files and .env only)
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_HOME="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
ENV_FILE="$REPO/.env"
SECRETS_DIR="$HOME/.config/claude-setup"
SECRETS="$SECRETS_DIR/secrets.env"
PREFS="$CLAUDE_HOME/preferences.md"
PROFILE="$CLAUDE_HOME/profile.md"
BACKUP="$CLAUDE_HOME/backups/claude-setup-$(date +%Y%m%d-%H%M%S)"
OFFLINE=0
[ "${1:-}" = "--offline" ] && OFFLINE=1

step() { printf '\n\033[1;36m▸ %s\033[0m\n' "$*"; }
ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }

# Points $2 at $1. Anything already there that is not a symlink is moved to the backup folder.
link() {
  local src="$1" dst="$2"
  mkdir -p "$(dirname "$dst")"
  if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then ok "$dst (ok)"; return; fi
  if [ -L "$dst" ]; then
    rm "$dst"
  elif [ -e "$dst" ]; then
    mkdir -p "$BACKUP"
    mv "$dst" "$BACKUP/"
    warn "previous $(basename "$dst") moved to $BACKUP"
  fi
  ln -s "$src" "$dst"
  ok "$dst → $src"
}

# Writes stdin to $1 only if the content changed. Prints "changed" or "unchanged".
write_if_changed() {
  local dst="$1" tmp
  tmp="$(mktemp)"; cat > "$tmp"
  if [ -f "$dst" ] && cmp -s "$tmp" "$dst"; then rm "$tmp"; echo unchanged
  else mkdir -p "$(dirname "$dst")"; mv "$tmp" "$dst"; echo changed; fi
}

step "Requirements"
for bin in git python3 node npx; do
  command -v "$bin" >/dev/null && ok "$bin" || { warn "missing $bin — install it and run again"; exit 1; }
done
HAS_CLAUDE=1
command -v claude >/dev/null && ok "claude $(claude --version 2>/dev/null | head -1)" \
  || { HAS_CLAUDE=0; warn "Claude Code not found (npm i -g @anthropic-ai/claude-code). MCP servers and plugins will be skipped."; }

step "Configuration (.env)"
if [ ! -f "$ENV_FILE" ]; then
  cp "$REPO/.env.example" "$ENV_FILE"
  warn ".env created from .env.example — fill it in and run ./install.sh again"
fi
added=$(python3 - "$REPO/.env.example" "$ENV_FILE" <<'PY'
import re, sys
example, env = open(sys.argv[1]).read().splitlines(), open(sys.argv[2]).read()
have = set(re.findall(r"^\s*([A-Z_][A-Z0-9_]*)=", env, re.M))
new = [l for l in example if (m := re.match(r"\s*([A-Z_][A-Z0-9_]*)=", l)) and m.group(1) not in have]
if new:
    with open(sys.argv[2], "a") as f:
        f.write("\n" + "\n".join(new) + "\n")
print(" ".join(l.split("=")[0] for l in new))
PY
)
[ -n "$added" ] && warn "new options appended to .env with their defaults: $added"
chmod 600 "$ENV_FILE"
set -a; . "$ENV_FILE"; set +a
ok "$SECRETS ($(write_if_changed "$SECRETS" < "$ENV_FILE"))"
chmod 600 "$SECRETS"
LINE='[ -f "$HOME/.config/claude-setup/secrets.env" ] && { set -a; . "$HOME/.config/claude-setup/secrets.env"; set +a; }'
for rc in "$HOME/.zshrc" "$HOME/.bashrc"; do
  [ -f "$rc" ] || continue
  grep -qF "claude-setup/secrets.env" "$rc" || { printf '\n# claude-setup\n%s\n' "$LINE" >> "$rc"; ok ".env variables exported in $(basename "$rc")"; }
done

step "Claude Code files (symlinks into this repo)"
link "$REPO/claude/CLAUDE.md"      "$CLAUDE_HOME/CLAUDE.md"
link "$REPO/claude/agents"         "$CLAUDE_HOME/agents"
link "$REPO/claude/hooks"          "$CLAUDE_HOME/hooks"
link "$REPO/claude/skills/commit"  "$CLAUDE_HOME/skills/commit"
chmod +x "$REPO"/claude/hooks/*
state=$(write_if_changed "$PREFS" <<EOF
<!-- Generated by claude-setup/install.sh from .env. Edit .env, not this file. -->
# User preferences
- Response language (also for subagents and vault notes): **${RESPONSE_LANGUAGE:-English}**.
- UI copy language in the apps you build: **${UI_LANGUAGE:-en-US}**.
- Language for code, commits and identifiers: **${CODE_LANGUAGE:-English}**.
EOF
)
ok "$PREFS ($state)"
if [ -f "$PROFILE" ]; then
  ok "$PROFILE (yours, untouched)"
else
  cp "$REPO/claude/profile.example.md" "$PROFILE"
  warn "$PROFILE created — describe yourself there (who you are, stacks, environment)"
fi

step "settings.json (merged, existing settings are kept)"
state=$(python3 - "$REPO/claude/settings.base.json" "$CLAUDE_HOME/settings.json" <<'PY'
import json, os, pathlib, sys
base = json.load(open(sys.argv[1]))
path = pathlib.Path(sys.argv[2])
cur = json.loads(path.read_text()) if path.exists() else {}
before = json.dumps(cur, sort_keys=True)

def merge(dst, src):
    for k, v in src.items():
        if k == "hooks":
            hooks = dst.setdefault("hooks", {})
            for event, entries in v.items():
                existing = hooks.setdefault(event, [])
                have = {h.get("command") for e in existing for h in e.get("hooks", [])}
                for entry in entries:
                    if not {h.get("command") for h in entry["hooks"]} <= have:
                        existing.append(entry)
        elif isinstance(v, dict) and isinstance(dst.get(k), dict):
            merge(dst[k], v)
        else:
            dst[k] = v

merge(cur, base)

if os.environ.get("DB_GUARD", "on").lower() == "off":
    pre = cur.get("hooks", {}).get("PreToolUse", [])
    for e in pre:
        e["hooks"] = [h for h in e.get("hooks", []) if "db-guard" not in h.get("command", "")]
    cur["hooks"]["PreToolUse"] = [e for e in pre if e["hooks"]]
    if not cur["hooks"]["PreToolUse"]:
        del cur["hooks"]["PreToolUse"]

if os.environ.get("DEFAULT_MODEL"):
    cur["model"] = os.environ["DEFAULT_MODEL"]
if os.environ.get("RESPONSE_LANGUAGE"):
    cur["language"] = os.environ["RESPONSE_LANGUAGE"]

if json.dumps(cur, sort_keys=True) != before:
    path.write_text(json.dumps(cur, indent=2, ensure_ascii=False) + "\n")
    print("changed")
else:
    print("unchanged")
PY
)
ok "$CLAUDE_HOME/settings.json ($state)"

step "Obsidian vault \"Claude Brain\""
if [ -n "${CLAUDE_BRAIN_DIR:-}" ]; then
  VAULT="${CLAUDE_BRAIN_DIR/#\~/$HOME}"
elif grep -qi microsoft /proc/version 2>/dev/null; then
  VAULT="/mnt/c/Claude Brain"
else
  VAULT="$HOME/Claude Brain"
fi
if [ -f "$VAULT/Home.md" ]; then
  ok "$VAULT (existing vault, untouched)"
else
  mkdir -p "$VAULT"/{Projects,Decisions,Sessions,Knowledge,Inbox}
  cp -rn "$REPO/vault/." "$VAULT/"
  ok "$VAULT (new vault created from the skeleton)"
fi
if [ -L "$HOME/claude-brain" ] || [ ! -e "$HOME/claude-brain" ]; then
  ln -sfn "$VAULT" "$HOME/claude-brain"
fi
[ -d "$VAULT/${VAULT_PROJECTS_DIR:-Projects}" ] \
  || warn "projects folder '$VAULT/${VAULT_PROJECTS_DIR:-Projects}' not found — check VAULT_PROJECTS_DIR in .env"
ok "shortcut ~/claude-brain. In Obsidian: Open folder as vault → $VAULT"

if [ "$OFFLINE" = 1 ] || [ "$HAS_CLAUDE" = 0 ]; then
  step "Skipping MCP servers, skills and plugins"
else
  step "MCP servers (user scope)"
  # Prints a header of MCP server $1 from ~/.claude.json (if $2 is given); exits 1 if the server doesn't exist.
  mcp_field() {
    python3 - "$@" <<'PY'
import json, pathlib, sys
p = pathlib.Path.home() / ".claude.json"
servers = json.loads(p.read_text()).get("mcpServers", {}) if p.exists() else {}
s = servers.get(sys.argv[1])
if s is None:
    sys.exit(1)
if len(sys.argv) > 2:
    print((s.get("headers") or {}).get(sys.argv[2], ""))
PY
  }
  add_mcp() {
    local name="$1"; shift
    if mcp_field "$name" >/dev/null; then ok "$name (already configured)"
    else claude mcp add --scope user "$name" "$@" >/dev/null && ok "$name"; fi
  }
  add_mcp context7 --transport http https://mcp.context7.com/mcp
  add_mcp playwright -- npx @playwright/mcp@latest
  add_mcp atlassian --transport http https://mcp.atlassian.com/v2/mcp
  if [ -n "${GITHUB_PAT:-}" ]; then
    current="$(mcp_field github Authorization 2>/dev/null || true)"
    if [ "$current" = "Bearer $GITHUB_PAT" ]; then
      ok "github (already configured)"
    else
      [ -n "$current" ] && claude mcp remove --scope user github >/dev/null 2>&1 || true
      claude mcp add --scope user --transport http github https://api.githubcopilot.com/mcp \
        --header "Authorization: Bearer $GITHUB_PAT" >/dev/null && ok "github (token updated from .env)"
    fi
  elif mcp_field github >/dev/null; then
    ok "github (already configured; GITHUB_PAT is empty in .env, kept the current token)"
  else
    warn "github: set GITHUB_PAT in .env and run again"
  fi
  warn "Atlassian uses OAuth: run /mcp inside Claude Code to log in, if you haven't yet"

  step "Third-party skills"
  [ -e "$CLAUDE_HOME/skills/supabase" ] && ok "supabase (already installed)" \
    || npx -y skills add supabase/agent-skills -g -a claude-code -s supabase -s supabase-postgres-best-practices -y
  [ -e "$CLAUDE_HOME/skills/find-skills" ] && ok "find-skills (already installed)" \
    || npx -y skills add vercel-labs/skills -g -a claude-code -s find-skills -y

  step "Official Jev plugin (TypeSafe)"
  if claude plugin list 2>/dev/null | grep -q "typesafe@typesafe-ai"; then ok "typesafe (already installed)"
  else
    claude plugin marketplace add typesafe-ai/skills >/dev/null 2>&1 || true
    claude plugin install typesafe@typesafe-ai >/dev/null && ok "typesafe@typesafe-ai"
  fi
fi

step "Done"
[ -n "${TYPESAFE_API_KEY:-}" ] && ok "Jev: key configured" || warn "Jev: TYPESAFE_API_KEY is empty in .env (the database guard uses regex only)"
[ "${DB_GUARD:-on}" = "off" ] && warn "DB_GUARD=off — database guard disabled"
echo "  Restart Claude Code to load changes to agents, hooks and settings."
